name: Website

on:
  push:
    paths: ["src/**", ".github/workflows/website.yml"]

  pull_request:
    paths: ["src/**", ".github/workflows/website.yml"]

env:
  NODE_VERSION: "21"
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Check for PR conflicts
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "has conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"

  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  es-lint:
    name: Check linting (es-lint)
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: PNPM Install
        uses: ./.github/actions/pnpm-install

      - name: Check ESlint
        run: pnpm lint

  prettier:
    name: Check formatting (prettier)
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: PNPM Install
        uses: ./.github/actions/pnpm-install

      - name: Check Prettier
        run: pnpm prettier --check .

  sveltecheck:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: PNPM Install
        uses: ./.github/actions/pnpm-install

      - name: Make dummy env for types
        run: |
          echo "ls -a ."
          ls -a .
          mv .env.example .env

      - name: Check Svelte
        run: pnpm run check

  build:
    name: Svelte Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Clone NotEnoughUpdates-REPO
        uses: actions/checkout@v3
        with:
          repository: NotEnoughUpdates/NotEnoughUpdates-REPO
          path: src/lib/constants/NotEnoughUpdates-REPO/items
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: PNPM Install
        uses: ./.github/actions/pnpm-install

      - name: Make dummy env for types
        run: |
          echo "ls -a ."
          ls -a .
          mv .env.example .env

      - name: Svelte Build
        run: pnpm run build
